### ISSUE TITLE
关于往届生团员关系

### ISSUE THREAD

**Issue by binlins** [sspkudx/admission_faq#12]
打电话回本科学校咨询了一波
得知
往届生 团组织关系有待转一说，若毕业时无团委老师联系办理，很可能仍处于本科学校。可寻学院团委老师办理，会给予介绍信一张。（时间原因未尝试）

**Comment by notfresh** [comment]
不错，可以的。但是不入党就搁那吧， 反正也没卵用了应该。

**Comment by notfresh** [comment]
翻群记录, 团员是开学以后在网上操作吗? 有人知道吗?

**Comment by notfresh** [comment]
转团关系刚在群里翻了一下, 更新了一下答案, 应该没啥毛病. 待验证.

**Comment by notfresh** [comment]
> 打电话回本科学校咨询了一波
> 得知
> 往届生 团组织关系有待转一说，若毕业时无团委老师联系办理，很可能仍处于本科学校。可寻学院团委老师办理，会给予介绍信一张。（时间原因未尝试）

老铁, 留下微信给你发个红包~

**Comment by notfresh** [comment]
发我邮件也可以, notfresh@foxmail.com
