### ISSUE TITLE
正经：培养计划，导师介绍?

### ISSUE THREAD

**Issue by notfresh** [sspkudx/admission_faq#7]

**Comment by Allen-Bayern** [comment]
请问同学是哪个方向的？求详细咨询的可以在底下留言

**Comment by notfresh** [comment]
我是软工的，可惜今年分不高，工作过两年，期望自己将来能做软件开发，做做产品经理，技术经理这种岗位
对自己认识比较清楚，感觉不擅长做算法，深度学习，神经网络的等某些热点技能等高端烧脑的东西
求学长介绍几个个软件工程方面不错的导师， 非常期待啊

**Comment by notfresh** [comment]
属于资质非常平庸的那种，向老老老实当个码农的那种

**Comment by ZhanXix** [comment]
求问安全方向的……
